apiVersion : apps/v1
kind: Deployment
metadata:
  name: dockerimg23
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dockerimg23
  template:
    metadata:
      labels:
        app: dockerimg23
    spec:
      containers:
        - name: acrdockergit 
          image: cont23.azurecr.io/dockerimg23:1388
          ports:
          - containerPort: 80
